export const ADD_INGREDIANT = "ADD_INGREDIANT";
export const REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const SET_INGREDIANTS = "SET_INGREDIANTS";
export const FETCH_INGREDIANTS_FAILED = "FETCH_INGREDIANTS_FAILED";

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCESS = "PURCHASE_BURGER_SUCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";
