export const ADD_INGREDIANT = "ADD_INGREDIANT";
export const REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const SET_INGREDIANTS = "SET_INGREDIANTS";
export const FETCH_INGREDIANTS_FAILED = "FETCH_INGREDIANTS_FAILED";
